name: dbt checkpoint one job

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:      

jobs:
  check-dbt-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Install dbt-checkpoint
        run: |
          python -m pip install --upgrade pip
          pip install dbt-checkpoint

      - name: Check model has description
        run: dbt-checkpoint check-model-description --models-path dbt_test_project

      - name: Check model columns have description
        run: dbt-checkpoint check-model-column-description  --models-path dbt_test_project

      - name: Check model has meta keys
        run: dbt-checkpoint check-model-has-meta-key --models-path dbt_test_project
