name: Deploy CS report to CS workspaces

on:
  workflow_dispatch:
    inputs:
      report:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - ClaimShop Standard
          - ClaimShop Benchmarks
      workspaces:
        description: 'Array of workspaces'
        required: true
        default: '["ALMBRAND_CS", "CODAN_CS", "CODANNO_CS", "FREMTIND_CS", "GF_CS", "GJENSIDIGE_CS", "KAB_CS", "LB_CS", "LOKAL_CS", "NEMFORSIKRING_CS", "POPERMO_CS", "THISTED_CS", "TOPDANMARK_CS", "TRYG_CS"]'
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ${{ fromJson(inputs.workspaces) }}
    name: Deploying ${{ matrix.workspace }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Deploy with Parameter
        run: |
          echo "Deploying ${{ matrix.workspace }} workspace..."