name: Deploy Default

run-name: >
  Deploy ${{ inputs.package }} to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: string
      scalepoint-repair-journey:
        description: 'Scalepoint Repair Journey'
        type: boolean
        default: true
      benchmark-master:
        description: 'Benchmark - Master'
        type: boolean
        default: true
      master-selskaber:
        description: 'Master - Selskaber'
        type: boolean
        default: true
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - AROS
          - AIG
          - CERTUS
          - CHUBB
          - DFA
          - DFIM
          - ETU
          - GARTNERNES
          - GF
          - GLOBAL
          - HF
          - HIMMERLAND
          - KAB
          - LB
          - LOKAL
          - NEMFORSIKRING
          - PENSAM
          - POPERMO
          - PROTECTOR-ARRIVA
          - PROTECTOR
          - SOENDERJYSK
          - STORSTROEMS
          - THISTED
          - VEJLEBRAND
          - VENDSYSSEL
          - VESTJYLLAND
          - VIKING
          - ZURICH
      scalepoint-repair-journey:
        description: 'Scalepoint Repair Journey'
        type: boolean
        default: true
      benchmark-master:
        description: 'Benchmark - Master'
        type: boolean
        default: true
      master-selskaber:
        description: 'Master - Selskaber'
        type: boolean
        default: true
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string

jobs:
  deploy:
    permissions:
        actions: read
        checks: write
        contents: read
        packages: read
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-workspace.yaml@13c69c6b0c5cbffe5dae9a143d916a4781d4c878
    with:
      environment: '${{ inputs.environment }}'
      package: '${{ inputs.package }}'
      report-list: '${{ toJSON(inputs) }}'
    secrets: inherit