name: Deploy All Workspaces

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string
        
permissions:
        actions: read
        checks: write
        contents: read
        packages: read
  
jobs:
  deploy-aros:
    if: always()
    name: Deploy ${{ inputs.package }} to AROS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'AROS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-aig:
    if: always()
    name: Deploy ${{ inputs.package }} to AIG
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'AIG'
      scalepoint-repair-journey: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-certus: 
    if: always()
    name: Deploy ${{ inputs.package }} to CERTUS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'CERTUS'
      scalepoint-repair-journey: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-chubb:
    if: always()
    name: Deploy ${{ inputs.package }} to CHUBB
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'CHUBB'
      scalepoint-repair-journey: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-concordia:
    if: always()
    name: Deploy ${{ inputs.package }} to CONCORDIA
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'CONCORDIA'
      benchmark-master: false
      master-selskaber: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-dfa:
    if: always()
    name: Deploy ${{ inputs.package }} to DFA
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'DFA'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-dfim:
    if: always()
    name: Deploy ${{ inputs.package }} to DFIM
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'DFIM'
      scalepoint-repair-journey: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-etu:
    if: always()
    name: Deploy ${{ inputs.package }} to ETU
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'ETU'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-gartnernes:
    if: always()
    name: Deploy ${{ inputs.package }} to GARTNERNES
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'GARTNERNES'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-gf:
    if: always()
    name: Deploy ${{ inputs.package }} to GF
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'GF'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-global:
    if: always()
    name: Deploy ${{ inputs.package }} to GLOBAL
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'GLOBAL'
      scalepoint-repair-journey: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-hf:
    if: always()
    name: Deploy ${{ inputs.package }} to HF
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'HF'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-himmerland:
    if: always()
    name: Deploy ${{ inputs.package }} to HIMMERLAND
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'HIMMERLAND'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-kab:
    if: always()
    name: Deploy ${{ inputs.package }} to KAB
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'KAB'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-lb:
    if: always()
    name: Deploy ${{ inputs.package }} to LB
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'LB'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-lokal:
    if: always()
    name: Deploy ${{ inputs.package }} to LOKAL
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'LOKAL'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-nemforsikring:
    if: always()
    name: Deploy ${{ inputs.package }} to NEMFORSIKRING
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'NEMFORSIKRING'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-pensam:
    if: always()
    name: Deploy ${{ inputs.package }} to PENSAM
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'PENSAM'
      benchmark-master: false
      master-selskaber: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-popermo:
    if: always()
    name: Deploy ${{ inputs.package }} to POPERMO
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'POPERMO'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-protector-arriva:
    if: always()
    name: Deploy ${{ inputs.package }} to PROTECTOR-ARRIVA
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'PROTECTOR-ARRIVA'
      scalepoint-repair-journey: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-protector:
    if: always()
    name: Deploy ${{ inputs.package }} to PROTECTOR
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'PROTECTOR'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-soenderjysk:
    if: always()
    name: Deploy ${{ inputs.package }} to SOENDERJYSK
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'SOENDERJYSK'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-storstroems:
    if: always()
    name: Deploy ${{ inputs.package }} to STORSTROEMS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'STORSTROEMS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-thisted:
    if: always()
    name: Deploy ${{ inputs.package }} to THISTED
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'THISTED'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-vejlebrand:
    if: always()
    name: Deploy ${{ inputs.package }} to VEJLEBRAND
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'VEJLEBRAND'
      package: ${{ inputs.package }}
    secrets: inherit   
  deploy-vendsyssel:
    if: always()
    name: Deploy ${{ inputs.package }} to VENDSYSSEL
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'VENDSYSSEL'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-vestjylland:
    if: always()
    name: Deploy ${{ inputs.package }} to VESTJYLLAND
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'VESTJYLLAND'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-viking:
    if: always()
    name: Deploy ${{ inputs.package }} to VIKING
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'VIKING'
      scalepoint-repair-journey: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-zurich:
    if: always()
    name: Deploy ${{ inputs.package }} to ZURICH
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-default.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'ZURICH'
      scalepoint-repair-journey: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-almbrand-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to ALMBRAND_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'ALMBRAND_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-codanno-cs: 
    if: always()
    name: Deploy ${{ inputs.package }} to CODANNO_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'CODANNO_CS'
      claimshop-benchmarks: false
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-codan-cs: 
    if: always()
    name: Deploy ${{ inputs.package }} to CODAN_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'CODAN_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-fremtind-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to FREMTIND_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'FREMTIND_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-gf-cs: 
    if: always()
    name: Deploy ${{ inputs.package }} to GF_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'GF_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-gjensidige-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to GJENSIDIGE_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'GJENSIDIGE_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-kab-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to KAB_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'KAB_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-lb-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to LB_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'LB_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-lokal-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to LOKAL_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'LOKAL_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-nemforsikring-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to NEMFORSIKRING_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'NEMFORSIKRING_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-popermo-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to POPERMO_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'POPERMO_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-thisted-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to THISTED_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'THISTED_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-topdanmark-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to TOPDANMARK_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'TOPDANMARK_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-tryg-cs:
    if: always()
    name: Deploy ${{ inputs.package }} to TRYG_CS
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-claimshop.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'TRYG_CS'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-almbrand-hp:
    if: always() 
    name: Deploy ${{ inputs.package }} to ALMBRAND_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'ALMBRAND_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-codan-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to CODAN_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'CODAN_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-gf-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to GF_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'GF_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-gjensidige-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to GJENSIDIGE_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'GJENSIDIGE_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-kab-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to KAB_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'KAB_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-lb-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to LB_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'LB_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-lokal-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to LOKAL_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'LOKAL_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-nemforsikring-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to NEMFORSIKRING_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'NEMFORSIKRING_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-popermo-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to POPERMO_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'POPERMO_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-topdanmark-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to TOPDANMARK_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'TOPDANMARK_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-tryg-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to TRYG_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'TRYG_HP'
      package: ${{ inputs.package }}
    secrets: inherit
  deploy-trygghansa-hp:
    if: always()
    name: Deploy ${{ inputs.package }} to TRYGGHANSA_HP
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-hub.yaml@0992430e48b2aeaa0243d86eb141dde1b0eabee3
    with:
      environment: 'TRYGGHANSA_HP'
      claimshop-benchmarks: false
      package: ${{ inputs.package }}
    secrets: inherit