name: Deploy Claimshop

run-name: >
  Deploy ${{ inputs.package }} to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: string
      claimshop-standard:
        description: 'ClaimShop Standard'
        type: boolean
        default: true
      claimshop-benchmarks:
        description: 'ClaimShop Benchmarks'
        type: boolean
        default: true
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - ALMBRAND_CS
          - CODAN_CS
          - CODANNO_CS
          - FREMTIND_CS
          - GF_CS
          - GJENSIDIGE_CS
          - KAB_CS
          - LB_CS
          - LOKAL_CS
          - NEMFORSIKRING_CS
          - POPERMO_CS
          - THISTED_CS
          - TOPDANMARK_CS
          - TRYG_CS
      claimshop-standard:
        description: 'ClaimShop Standard'
        type: boolean
        default: true
      claimshop-benchmarks:
        description: 'ClaimShop Benchmarks'
        type: boolean
        default: true
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string

jobs:
  deploy:
    permissions:
        actions: read
        checks: write
        contents: read
        packages: read
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-workspace.yaml@13c69c6b0c5cbffe5dae9a143d916a4781d4c878
    with:
      environment: '${{ inputs.environment }}'
      package: '${{ inputs.package }}'
      report-list: '${{ toJSON(inputs) }}'
    secrets: inherit