name: Deploy Hub Property

run-name: >
  Deploy ${{ inputs.package }} to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: string
      hub-property-standard:
        description: 'Hub Property Standard'
        type: boolean
        default: true
      hub-property-benchmarks:
        description: 'Hub Property Benchmarks'
        type: boolean
        default: true
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - ALMBRAND_HP
          - CODAN_HP
          - GJENSIDIGE_HP
          - GF_HP
          - KAB_HP
          - LB_HP
          - LOKAL_HP
          - NEMFORSIKRING_HP
          - POPERMO_HP
          - TOPDANMARK_HP
          - TRYG_HP
          - TRYGGHANSA_HP
      hub-property-standard:
        description: 'Hub Property Standard'
        type: boolean
        default: true
      hub-property-benchmarks:
        description: 'Hub Property Benchmarks'
        type: boolean
        default: true
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string

jobs:
  deploy:
    permissions:
        actions: read
        checks: write
        contents: read
        packages: read
    uses: scalepoint/bi-powerbi/.github/workflows/deploy-workspace.yaml@13c69c6b0c5cbffe5dae9a143d916a4781d4c878
    with:
      environment: '${{ inputs.environment }}'
      package: '${{ inputs.package }}'
      report-list: '${{ toJSON(inputs) }}'
    secrets: inherit