name: Deploy HP report to HP workspaces

on:
  workflow_dispatch:
    inputs:
      report:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - Hub Property Standard
          - Hub Property Benchmarks
      workspaces:
        description: 'Array of workspaces'
        required: true
        default: '["ALMBRAND_HP", "CODAN_HP", "GF_HP", "GJENSIDIGE_HP", "KAB_HP", "LB_HP", "LOKAL_HP", "NEMFORSIKRING_HP", "POPERMO_HP", "TOPDANMARK_HP", "TRYGGHANSA_HP", "TRYG_HP"]'
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ${{ fromJson(inputs.workspaces) }}
    name: Deploying ${{ matrix.workspace }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Deploy with Parameter
        run: |
          echo "Deploying ${{ matrix.workspace }} workspace..."