name: Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      actions: read
      checks: write
      contents: read
      packages: write
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        id: get-version
        uses: scalepoint/actions/get-semver@v1
        with:
          main_version: "1.1.1"
      - name: Import build content
        uses: actions/download-artifact@v4
        with:
          name: build-content
      - name: Extract imported archive
        run: |
          Expand-Archive build-content.zip -DestinationPath .\build -Verbose
      - name: Compress build content
        env:
          BUILD_DIR: "build"
        run: |
          Write-Verbose 'Compressing build content...'
          Compress-Archive -Path (Join-Path $Env:BUILD_DIR '*') -Destination '.\build.zip' -Verbose
      - name: Setup ORAS
        uses: oras-project/setup-oras@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: github
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Store binaries
        run: oras push ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version }} .\build.zip
