name: Reset DW

run-name: >
  Reload ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'DW to reset'
        required: true
        type: choice
        options:
          - Tenant1
          - Tenant2
          - Tenant3
          - Tenant4
          - Tenant5
          - Tenant6

  workflow_call:
    inputs:
      environment:
        description: 'Environment to reset'
        required: true
        type: string

jobs:
  reset-dw:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Truncate '${{ inputs.environment }}'
        shell: pwsh
        run: |

          Write-Host ('Truncated ${{ inputs.environment }}')
