name: Reset Stage DWs

run-name: >
  Reload ${{ inputs.environments }}

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Environments to reset'
        required: true
        default: '["Tenant1", "Tenant2", "Tenant3", "Tenant4", "Tenant5", "Tenant6"]'
        type: string
  schedule:
    - cron: '*/7 * * * *'
    - cron: '*/20 * * * *'
    - cron: '*/40 * * * *'
    #- cron: '0 0 1-7 * 6' # First Saturday of the month
    #- cron: '0 0 8-14 * 6' # Second Saturday of the month
    #- cron: '0 0 15-21 * 6' # Third Saturday of the month

    
jobs:
  reset-dw:
    name: reset ${{ matrix.environment }} DW
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
    permissions:
        actions: read
        checks: write
        contents: read
        packages: read
    uses: SerhiiBasetskyi/testGHActions/.github/workflows/reload.yaml@main
    with:
      environment: '${{ matrix.environment }}'
    secrets: inherit
    
  auto-reset-dw:
    if: ${{ github.event_name == 'schedule' && github.event.schedule == matrix.cron }}
    name: Auto reset ${{ matrix.environment }} DW
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        include:
          - cron: '*/5 * * * *'
            environments: ["Tenant1", "Tenant2", "Tenant3"]
          - cron: '*/15 * * * *'
            environments: ["Tenant4", "Tenant5"]
          - cron: '30 * * * *'
            environments: ["Tenant6"]
    permissions:
      actions: read
      checks: write
      contents: read
      packages: read
    steps:
      - name: Run reset-dw job
        uses: ./.github/workflows/reset-dw
        with:
          environments: ${{ toJson(matrix.environments) }}