name: Deploy Tenant report to Tenant workspaces

on:
  workflow_dispatch:
    inputs:
      report:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - Scalepoint Repair Journey
          - Benchmark - Master
          - Master - Selskaber
      workspaces:
        description: 'Array of workspaces'
        required: true
        default: '["AROS", "AIG", "CERTUS", "CHUBB", "DFA", "DFIM", "ETU", "GARTNERNES", "GF", "GLOBAL", "HF", "HIMMERLAND", "KAB", "LB", "LOKAL", "NEMFORSIKRING", "PENSAM", "POPERMO", "PROTECTOR-ARRIVA", "PROTECTOR", "SOENDERJYSK", "STORSTROEMS", "THISTED", "VEJLEBRAND", "VENDSYSSEL", "VESTJYLLAND", "VIKING", "ZURICH"]'
      package:
        description: 'Package tag in the remote registry'
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ${{ fromJson(inputs.workspaces) }}
    name: Deploying ${{ matrix.workspace }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Deploy with Parameter
        run: |
          echo "Deploying ${{ matrix.workspace }} workspace..."